services:
  - type: web
    name: mafioso-server
    runtime: node
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 4000
